version: '3'

services:
  db:
    container_name: container-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=senha_mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306